#BANNER
banner:
  charset: UTF-8
  location: banner.txt

server:
  port : 8080
  
#CONFIGURATIONS
spring:
  application:
    name: auditor
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate.ddl-auto: update
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auditor
    username: postgres
    password: 5432
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    suffix: .html
    
  data:
    mongodb: 
      host: localhost
      port: 27017
      database: mensajes
  